export const HOME_CONTENT = {
    en: {
        heroWelcome: "Welcome to",
        churchName: "St. John the Baptist Ukrainian Catholic Church",
        humanitarianBtn: "Humanitarian Aid Drive",
        liturgySchedTitle: "Divine Liturgy Schedule",
        saturday: "Saturday",
        sunday: "Sunday",
        holyDays: "Holy Days",
        specialIntentions: "Special Intentions (Weekdays)",
        ua: "Ukrainian",
        en: "English",
        summary: "Condimentum id venenatis a condimentum. Sed enim ut sem viverra aliquet eget. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Aliquet bibendum enim facilisis gravida neque convallis. At tempor commodo ullamcorper a lacus. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Id semper risus in hendrerit gravida. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Tincidunt ornare massa eget egestas purus. Risus in hendrerit gravida rutrum quisque non tellus orci. Neque vitae tempus quam pellentesque nec nam aliquam.",
        easterCeleb: "Easter Celebration at St. John the Baptist Catholic Church",
        supportTitle: "Support Your Parish",
        supportBtn: "Support our Church",
        supportParishBtn: "Support our Parish",
        history: "Founded in 1921, our church is located in the heart of historic Morris County, five miles from Morristown, in the town of Whippany, New Jersey. It is a very active and growing parish with a new campus that includes our newly consecrated church as well as the 24,000 square foot Ukrainian American Cultural Center of NJ.",
        ourChurch: "Our Church",
    },
    ua: {
        heroWelcome: "Вітаємо в",
        churchName: "Українській Католицькій Церкві Св. Івана Хрестителя",
        humanitarianBtn: "Проєкти Гуманітарної Допомоги",
        liturgySchedTitle: "Розклад Божественних Літургій",
        saturday: "Субота",
        sunday: "Неділя",
        holyDays: "Свята",
        specialIntentions: "Особливі Потреби (Будні Дні)",
        ua: "Українською",
        en: "Англійською",
        summary: "UA | Condimentum id venenatis a condimentum. Sed enim ut sem viverra aliquet eget. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Aliquet bibendum enim facilisis gravida neque convallis. At tempor commodo ullamcorper a lacus. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Id semper risus in hendrerit gravida. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Tincidunt ornare massa eget egestas purus. Risus in hendrerit gravida rutrum quisque non tellus orci. Neque vitae tempus quam pellentesque nec nam aliquam.",
        easterCeleb: "Святкування Великодня у Нашій Церкві",
        supportTitle: "Підтримати Нашу Парафію",
        supportBtn: "Підтримати Нашу Церкву",
        supportParishBtn: "Підтримати Нашу Парафію",
        history: "UA | Founded in 1921, our church is located in the heart of historic Morris County, five miles from Morristown, in the town of Whippany, New Jersey. It is a very active and growing parish with a new campus that includes our newly consecrated church as well as the 24,000 square foot Ukrainian American Cultural Center of NJ.",
        ourChurch: "Наша Церква",
    }
}